#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandrake Linux
# Module          : rpm-helper
# File            : add-service
# Version         : $Id$
# Author          : Frederic Lepied
# Created On      : Mon Jul  8 08:14:34 2002
# Purpose         : helper script for rpm scriptlets to add a
#		    service.
#---------------------------------------------------------------

if [ $# != 3 ]; then
    echo "usage: $0 <pkg name> <number installed> <service name>" 1>&2
    exit 1
fi

pkg=$1				# name of the package
num=$2				# number of packages installed
srv=$3				# name of the service

if [ $num = 1 ]; then
    /sbin/chkconfig --add $srv
else
    if [ -f /var/lock/subsys/$srv ]; then
	/sbin/service $srv restart > /dev/null 2>/dev/null || :
	# restart services that depend of portmap
	if [ $srv = portmap ]; then
	    for s in amd autofs bootparamd clusternfs mcserv nfs nfslock ypserv ypbind yppasswdd ypxfrd; do
		if [ -f /var/lock/subsys/$s ]; then
		    /sbin/service $s restart > /dev/null 2>/dev/null || :
		fi
	    done
	fi
    fi
fi

# add-service ends here
