#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandriva Linux
# Module          : rpm-helper
# File            : del-service
# Version         : $Id$
# Author          : Frederic Lepied
# Created On      : Tue Jul  9 08:11:26 2002
# Purpose         : helper script for rpm scriptlets to remove a
#		    service.
#---------------------------------------------------------------

if [ $# != 3 ]; then
    echo "usage: $0 <pkg name> <number installed> <service name>" 1>&2
    exit 1
fi

pkg=$1				# name of the package
num=$2				# number of packages installed
srv=$3				# name of the service

systemd=no
[ -x /bin/systemctl -a -r /lib/systemd/system/${srv}.service ] && systemd=yes

if [ $num = 0 ]; then
    if [ -z "$DURING_INSTALL" ]; then
	/sbin/service $srv stop > /dev/null || :
    fi

    # support for systemd. chkconfig will do daemon-reload for us
    if [ $systemd = yes ]; then
	    /bin/systemctl --quiet --no-reload disable ${srv}.service
    fi
    /sbin/chkconfig --del $srv
fi

# del-service ends here
