#!/bin/sh
# $Id$
# helper script for rpm scriptlets to get a random password

if [ -n "$1" ]; then
    length=$1
else
    length=8
fi

perl -e "@c = (a..z,A..Z,0..9); print map { @c[rand @c] } 0..$length"
