#!/bin/sh
# $Id$
# helper script for rpm scriptlets to get a free syslog local facility

if [ -f /etc/syslog.conf ]; then
    cntlog=0
    while grep -q local${cntlog} /etc/syslog.conf; do 
	cntlog=$((cntlog+1));
    done
    echo local${cntlog}
fi
