#!/bin/sh
# $Id$
# helper script for rpm scriptlets to get a free syslog local facility

if [ -f /etc/syslog.conf ]; then
    for (( i=0; i <= 7; i++ )); do
	if ! grep -q "^local$i" /etc/syslog.conf; then
	    echo "local$i"
	    break
	fi
    done
fi
