#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandrake Linux
# Module          : rpm-helper
# File            : get-password
# Version         : $Id: del-user,v 1.1.1.1 2002/07/09 15:04:21 flepied Exp $
# Author          : Guillaume Rousse
# Created On      : Thu Apr  1 00:00:46 2004
# Purpose         : helper script for rpm scriptlets to generate
#		    a random password
#---------------------------------------------------------------

if [ -n "$1" ]; then
    length=$1
else
    length=8
fi

perl -e "@c = (a..z,A..Z,0..9); print map { @c[rand @c] } 0..$length"

# get-password ends here
