#############################################################################
# File		: Makefile
# Package	: rpm-helper
# Author	: Frederic Lepied
# Created on	: Mon Sep 30 13:20:18 1999
# Version	: $Id$
# Purpose	: rules to manage the files.
#############################################################################

PACKAGE = rpm-helper
VERSION := $(shell rpm -q --qf %{VERSION} --specfile $(PACKAGE).spec)
RELEASE := $(shell rpm -q --qf %{RELEASE} --specfile $(PACKAGE).spec)
TAG := $(shell echo "V$(VERSION)_$(RELEASE)" | tr -- '-.' '__')

FILES = AUTHORS README README.CVS COPYING ChangeLog Makefile \
       $(PACKAGE).spec $(SCRIPTS)
SCRIPTS = add-user del-user add-service del-service create-file \
	add-group del-group

LIBDIR=/usr/share/rpm-helper

all:
	@echo "done"

clean:
	rm -f *~ $(PACKAGE)*.tar.bz2

install:
	-mkdir -p $(DESTDIR)$(LIBDIR)
	cp -p $(SCRIPTS) $(DESTDIR)$(LIBDIR)

version:
	@echo "$(VERSION)-$(RELEASE)"

# rules to build a test rpm

localrpm: localdist buildrpm

localdist: cleandist dir localcopy tar

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.bz2

dir:
	mkdir $(PACKAGE)-$(VERSION)

localcopy:
	tar c $(FILES) | tar x -C $(PACKAGE)-$(VERSION)

tar:
	tar cvf $(PACKAGE)-$(VERSION).tar $(PACKAGE)-$(VERSION)
	bzip2 -9vf $(PACKAGE)-$(VERSION).tar
	rm -rf $(PACKAGE)-$(VERSION)

buildrpm:
	rpm -ta $(PACKAGE)-$(VERSION).tar.bz2

# rules to build a distributable rpm

rpm: changelog cvstag dist buildrpm

dist: cleandist dir export tar

export:
	cvs export -d $(PACKAGE)-$(VERSION) -r $(TAG) $(PACKAGE)

cvstag:
	cvs tag $(CVSTAGOPT) $(TAG)

changelog: ../common/username
	cvs2cl -U ../common/username -I ChangeLog 
	rm -f ChangeLog.bak
	cvs commit -m "Generated by cvs2cl the `date '+%d_%b'`" ChangeLog

# Makefile ends here
