#!/bin/sh
#---------------------------------------------------------------
# Project         : Mandriva Linux
# Module          : rpm-helper
# File            : verify-shell
# Version         : $Id$
# Author          : Thierry Vignaud
# Created On      : Tue Nov  5 13:52:20 2002
# Purpose         : helper script for rpm scriptlets to check a
#		    shell is in /etc/shells
#---------------------------------------------------------------

if [ $# != 3 ]; then
    echo "usage: $0 <pkg name> <number installed> <shell name>" 1>&2
    exit 1
fi

pkg=$1				# name of the package
num=$2				# number of packages installed
shl=$3				# name of the shell

CFG_FILE=/etc/shells


echo -n "Looking for $shl in /etc/shells... "
if ! grep "^/bin/${shl}\$" /etc/shells > /dev/null; then
    echo "missing"
    echo "${shl} missing from /etc/shells" >&2
else
    echo "found"
fi
